### How to reverse a string

In [1]:
def reverse(s): 
  str = "" 
  for i in s: 
    str = i + str
  return str

In [8]:
s = "GSharmaJii"
print(len(s))

10


In [26]:
# Function to reverse a string 
def reverse(string): 
    string = "".join(reversed(string)) 
    return string 

In [27]:
print(reverse(s))

iiJamrahSG


In [28]:
# Function to reverse a string 
def reverse(string): 
    string = string[::-1] 
    return string 

In [5]:
"".join(reversed("GAuav"))

'vauAG'

## Del vs Remove

In [14]:
l = [1,2,5,6,7]

In [15]:
del l[3] # it removes the value at index 3

In [16]:
l

[1, 2, 5, 7]

In [17]:
l = [1,2,5,6,7]

In [18]:
l.remove(7) # it removes the value specified in the brackets from the list

In [19]:
l

[1, 2, 5, 6]

## File

In [ ]:
#open a file:

with open('path','mode',encoding='') as f:  # with is a context manager

    
#using with keyword we need not close the file

In [ ]:
with open("test.txt",'w',encoding = 'utf-8') as f:
    f.write("my first file\n")
    f.write("This file\n\n")
    f.write("contains three lines\n")

   

## append() vs Extend()

In [33]:
list1,list2=[1,2,3],[5,6,7,8]


In [34]:
list1.append(2)

In [35]:
list1

[1, 2, 3, 2]

In [36]:
list1.extend(list2) #this extends list1 in place

In [37]:
list1

[1, 2, 3, 2, 5, 6, 7, 8]

In [ ]:
## String concatination only works if all the elements are string or else TypeError

In [42]:
nums=[1, 2, 3, 2, 5, 6, 7, 8]

In [43]:
for i in nums:
    if i<5:
        nums.remove(i)

In [49]:
nums

[2, 2, 5, 6, 7, 8]

In [50]:
list(filter(lambda x:x>5,nums))

[6, 7, 8]

## enumerate()

In [56]:
for i,v in enumerate(['Python','C++','Scala']):
    print(i,v)

0 Python
1 C++
2 Scala


In [55]:
for i,v in enumerate(['Python','C++','Scala'],start=102):
    print(i,v)

102 Python
103 C++
104 Scala


## star

In [ ]:
*
**
***
****
*****

In [61]:
for i in range(0,5):
    for j in range(0,i+1):
        print('*',end='')
    print()

*
**
***
****
*****


In [7]:
A0= {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
A1=range(5)

In [8]:
[i for i in A1 if i in A0]

[]

## check duplicate char in String

In [35]:
## initializing string
string = "Gsharmajii"
## initializing a list to append all the duplicate characters
duplicates = []
for char in string:
   ## checking whether the character have a duplicate or not
   ## str.count(char) returns the frequency of a char in the str
   if string.count(char) > 1:
   ## appending to the list if it's already not present
       if char not in duplicates:
           duplicates.append(char)
print(" ".join(duplicates))

a i


In [3]:
stringsss = "gafg"
duplicate= []

for char in stringsss:
    if stringsss.count(char) > 1:
        if char not in duplicate:
            duplicate.append(char)
print(" ".join(duplicate))

g


## Check Duplicate in a List

In [33]:
list1 = [1,2,3,4,5,5,5,5,9,6,6,6,7,2,3]
list2 = sorted(list1)
count= len(list2)
duplicate =set([])
for i in range(0,count-1):
    if list2[i-1] == list2[i]:
        duplicate.add(list2[i])
        
print(''.join(str(duplicate)))



{2, 3, 5, 6}


In [13]:
{num} is not an armstrong number

12


In [39]:
def checkIfDuplicates_3(listOfElems):
    ''' Check if given list contains any duplicates '''    
    for elem in listOfElems:
        if listOfElems.count(elem) > 1:
               return True
    return False

In [41]:
list4=[1,2,4,5]
checkIfDuplicates_3(list4)

False

## Remove white space

In [41]:
s = '  Hello  World   From Gauravjii \t\n\r\tHi There  '

In [42]:
s.strip()
s.rstrip()
s.lstrip()

'Hello  World   From Gauravjii \t\n\r\tHi There  '

In [43]:
s.replace(" ", "") 
#We can use replace() to remove all the whitespaces from the string

'HelloWorldFromGauravjii\t\n\r\tHiThere'

In [44]:

" ".join(s.split())
#remove duplicate whitespaces and newline characters, then you can use join() function with string split() function.


'Hello World From Gauravjii Hi There'

## Check if the lists are same

In [ ]:
list1=[1,2,5,3]
list2=[1,2,3,5]

In [54]:


list1.sort() 
list2.sort() 
  
# using == to check if  
# lists are equal 
if list1 == list2: 
    print ("The lists are identical") 
else : 
    print ("The lists are not identical") 

The lists are identical


## Anagram program
Two strings are said to be anagram if they contain same set of characters but in different order. For example, “Mother In Law” and “Hitler Woman” are anagrams.

In [57]:
def check(s1, s2): 
      
    # the sorted strings are checked  
    if(sorted(s1) == sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 

#s1=[1,2,5,3]
#s2=[1,2,3,5]
check(s1, s2) 



The strings aren't anagrams.


## Armstrong number program
A number is called an Armstrong number if it is equal to sum of its digits each raised to the power of number of digits in it

In [19]:
def IsArmstrongg(num):
    count= int(len(num))
    sumtotal=0
    for char in num:
        sumtotal += int(char) ** count
        
    if sumtotal == int(num):
        print(f"{num} is an armstrong number")
    else:
        print(f"{num} is not an armstrong number")

In [20]:
num = input("Enter the number to check the Armstrong:")
IsArmstrongg(num)

Enter the number to check the Armstrong:111.5


ValueError: invalid literal for int() with base 10: '.'

## Palindrom number

In [64]:
def checkPalindrome(s):
    forward = s[::]
    backward= s[::-1]
    if forward == backward:
        return True
    else:
        return False

## Factorial of a Given Number

In [ ]:
def factorial1(n):
    j=1
    count = 1
    while j <= n:
        count = count*j
        j +=1
    return (f"The factorial for {n} is {count}.")

n = int(input("Enter the number of which you want factorial:"))
factorial1(n)

In [9]:
#Factorial using reccursion:
   
def fact(n):
    if n == 0:
        return 1
    else:
        return n * fact(n-1)
    

def fact1(n):
    j=1
    count = 1
    while j<=n:
        count *= j
        j+=1
    return (count)

In [10]:
result = fact1 (5)
print(result)

120


## String to list and list to string

lists, tuples, and strings are iterables

In [99]:
s = 'Gaurav Sharma'   #string to list
slist= s.split()

In [100]:
slist

['Gaurav', 'Sharma']

In [105]:
lists="-".join(slist)   #list to string

In [106]:
lists

'Gaurav-Sharma'

In [12]:
x=['ab','cd']
for i in map(list,x):
    print(i)

['a', 'b']
['c', 'd']


## Armstrong number

In [128]:
def IsArmstrongg(num):
    count= int(len(num))
    sumtotal=0
    for char in num:
        sumtotal += int(char) ** count
        
    if sumtotal == int(num):
        print(f"{num} is an armstrong number")
    else:
        print(f"{num} is not an armstrong number")

Enter the number to check the Armstrong:370
370 is an armstrong number


## Fibonacci Geneator and Fibonacci 

In [2]:
def fibReturn(n):
    a, b = 0, 1
    series=[]
    for i in range(n):
        series.append(a)
        a, b = b, a + b
    return series

In [3]:
def fibGenerate(n):
    a, b = 0, 1
    for i in range(n):
        yield a
        a, b = b, a + b

## pangra

Note : Pangrams are words or sentences containing every letter of the alphabet at least once.
For example : "The quick brown fox jumps over the lazy dog"

In [73]:
import string
def func(str1, alphabet =string.ascii_lowercase):
    alphaset = set(alphabet)  
    return alphaset <= set(str1.lower())  

In [74]:
func('Gaurav')

False

In [75]:
func('The quick brown fox jumps over the lazy dog')

True

## Metrix operation

In [52]:
import numpy
np.set_printoptions(legacy='1.13')
# Two matrices are initialized by value
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])


In [53]:
#  add()is used to add matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])
print ("Addition of two matrices: ")
print (numpy.add(x,y))

Addition of two matrices: 
[[ 8 10]
 [13 15]]


In [49]:
# subtract()is used to subtract matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

print ("Subtraction of two matrices : ")
print (numpy.subtract(x,y))

Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]


In [54]:
# divide()is used to divide matrices

x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

print ("Matrix Division : ")
print (numpy.divide(x,y))

Matrix Division : 
[[ 0.14285714  0.25      ]
 [ 0.44444444  0.5       ]]


In [56]:
print ("Multiplication of two matrices: ")
print (numpy.multiply(x,y))

Multiplication of two matrices: 
[[ 7 16]
 [36 50]]


In [55]:
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])


print ("The product of two matrices : ")
print (numpy.dot(x,y))

The product of two matrices : 
[[25 28]
 [73 82]]


In [57]:
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])


print ("square root is : ")
print (numpy.sqrt(x))

square root is : 
[[ 1.          1.41421356]
 [ 2.          2.23606798]]


In [59]:
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

print ("The summation of elements : ")
print (numpy.sum(y))

The summation of elements : 
34


In [58]:
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

print ("The column wise summation  : ")
print (numpy.sum(y,axis=0))

The column wise summation  : 
[16 18]


In [ ]:
print ("The row wise summation: ")
print (numpy.sum(y,axis=1))

In [60]:
# using "T" to transpose the matrix
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

print ("Matrix transposition : ")
print (x.T)

Matrix transposition : 
[[1 4]
 [2 5]]


 ## find second largest number in an integer array

In [1]:
nums = [1,2,3,4,5,6,78,44,44,11,55,65,88,552,3,6]

In [17]:
GAURAV=sorted(nums) #RETURNS a new sorted list

In [18]:
GAURAV[-2]

88

In [14]:
nums.sort() #changes the original list RETURNS NOTHING

In [19]:
nums[-2]

88

## Sum of the even numbers in the list

In [20]:
def findSum(nums):
    total=0
    for num in nums:
        if num%2==0:
            total+=num
    return total

In [21]:
nums=[2,5,8,9,6,4,7,8,4]

In [22]:
findSum(nums)

32

## How to count occurrences of each character in a string 

In [38]:
def countchar(string1):
    dictcount={}
    for s in string1:
        if s in dictcount.keys():
            dictcount[s] += 1
        else:
            dictcount[s] = 1
    
    return dictcount


In [39]:
name="Gauravsharma"
countchar(name)

{'G': 1, 'a': 4, 'u': 1, 'r': 2, 'v': 1, 's': 1, 'h': 1, 'm': 1}

or we can use collection.counter

In [42]:
from collections import Counter

In [44]:
res = Counter(name)

In [45]:
res

Counter({'G': 1, 'a': 4, 'u': 1, 'r': 2, 'v': 1, 's': 1, 'h': 1, 'm': 1})

## How to find largest number less than a given number and without a given digit

In [55]:
digit1=int(input("Enter the number"))
digit2=int(input("Enter the number"))

Enter the number143
Enter the number2


In [56]:
digit2
digit1

143

In [65]:
def findsecondlargest(nums,digit1,digit2):
    sortednum= sorted(nums)
    sortedlistwithoutdigit2=[]
    for num in sortednum:
        if str(digit2) not in str(num):
            if num < digit1:
                sortedlistwithoutdigit2.append(num)
    return sortedlistwithoutdigit2[-1]
            

In [68]:
nums=[111,140,524,142,144]

In [69]:
findsecondlargest(nums,digit1,digit2)

140

## How to find number of pairs in a list whose sum is equal to given number

In [205]:
nums = [25,12,8,10]
sum1 = 20

In [206]:
def findpairsforSum(nums,sum1):
    pairs=()
    list_pairs=[]
    
    for i in range(len(nums)):
        if nums[i] < sum1:
            
            for j in range(i+1,len(nums)):
                
                if nums[i] + nums[j] == sum1:
                    pairs = pairs + (nums[i],nums[j])
                    list_pairs.append(pairs)
                    pairs=()   
                    
    return list_pairs
            
        


In [207]:
findpairsforSum(nums,sum1)

[(12, 8)]

## How to find continuous sub array whose sum is equal to given number

## How to remove duplicate elements from List

#set automatically sorts the numbers too

In [219]:
nums=[12,1,2,4,66,5,8,7,6,3,4,8,5]

In [220]:
def removeDuplicate(nums):
    return set(nums)

In [221]:
removeDuplicate(nums)

{1, 2, 3, 4, 5, 6, 7, 8, 12, 66}

## How to check whether given number is binary 

In [264]:
numm = 10101100100

In [265]:
def checkBinary(num):
    for n in str(num):
        if n not in ['0','1']:
            return "Not Binary"
    
    return "Binary"

In [266]:
checkBinary(numm)

'Binary'

## How to check whether one string is a rotation of another

In [354]:
def checkRotation(s1,s2):
    if len(s1) == len(s2):
        print("roation of each other") if s2 in s1+s1 else print("not a roation of each other")
    else:
        return ("not a roation of each other")

In [355]:
s1= "abcde"
s2= "bacde"

checkRotation(s1,s2)

not a roation of each other


## How to check whether one string has same characters and length as the other

In [356]:
def checkifIncludes(s1,s2):
    if len(s1) == len(s2):
        for char in s2:
            if char not in s1:
                return ("No")
        else: return ("Yes")
    else:
        return ("no")

In [362]:
s1= "abcdef"
s2= "bacdec"

In [363]:
checkifIncludes(s1,s2)

'Yes'

## How to find intersection of two arrays

In [371]:
## set removes duplicates and also sorts the array

In [372]:
def intersactionoflist(list1,list2):
    inter=[]
    for l in set(list1):
        if l in set(list2):
            inter.append(l)
    return inter

In [373]:
list1=[1,5,6,8,7,4,1,2,5,6,3]
list2=[2,5,8,6,9,4,2,3]

intersactionoflist(list1,list2)

[2, 3, 4, 5, 6, 8]

## Check if the input is number or string

In [ ]:
an input can be int, float or string 
but when we use input() method its always a string
we need to explicitly convert it to int or float

In [374]:
def checktype(user_input):
    try:
        val = int(user_input)
        print("Input is an integer number. Number = ", val)
    except ValueError:
        try:
            val = float(user_input)
            print("Input is a float  number. Number = ", val)
        except ValueError:
            print("No.. input is not a number. It's a string")

In [378]:
user_input = input("Enter your Age")
checktype(user_input)

Enter your Ageguaravb
No.. input is not a number. It's a string


In [397]:
isinstance(float(input()),int)

25.6


False

In [396]:
int(25.2)

25

In [428]:
list1=[14, 0, 5, 2, 0, 3, 0]
listzeros=[]
count=list1.count(0)

In [433]:
for i in range(count-1):
    x = list1.pop(list1.index(0))
    listzeros.append(x)

ValueError: 0 is not in list

In [430]:
x

0

In [417]:
list1.pop(list1.index(0))

0

In [418]:
list1

[14, 5, 2, 0, 3, 0]

In [419]:
list1.pop(list1.index(0))

0

In [420]:
list1

[14, 5, 2, 3, 0]