In [1]:
import numpy as np

In [2]:
angles = np.array([0,30,45,60,90])

In [3]:
angles

array([ 0, 30, 45, 60, 90])

In [10]:
angles_radians = angles * np.pi/180
angles_radians

#The radian is a unit of measure for angles used mainly in trigonometry.
#It is used instead of degrees. 
#Whereas a full circle is 360 degrees, a full circle is just over 6 radians. A full circle has 2π radians (Roughly 6.28).
# a radian is defined by an arc of a circle.
#radian = π*degree /180
#degree=180*radian/π

#1radian = 57.3 degrees

#we need to calculate the angles in radian and not with 0 30 45 60 90

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [11]:
ang=360*np.pi/180

In [6]:
ang

6.283185307179586

In [13]:
np.sin(30)

-0.9880316240928618

In [15]:
np.sin(1.57079633)

1.0

In [16]:
angles_radians= np.radians(angles)   #np function to convert degree to radian

In [17]:
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [22]:
angle_degrees=np.array(np.degrees(angles_radians),dtype=np.int16)

In [23]:
angle_degrees

array([ 0, 29, 45, 59, 90], dtype=int16)

In [ ]:
#Sin Cos tan in np

In [26]:
print(f"Cosine of angles in the array:\n{np.cos(angles_radians)}")

Cosine of angles in the array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [27]:
print(f"Tangent of angles in the array:\n{np.tan(angles_radians)}")

Tangent of angles in the array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [28]:
sin=np.sin(angles_radians)

print(f"Sine Inverse of angles in the array:\n{np.arcsin(sin)}")

Sine Inverse of angles in the array:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [ ]:
np.mean(some_array)

In [ ]:
np.median(some_array)

delimiter for a csv file is always a comma

In [ ]:
#we can generate an array of the data from reading a csv file 

In [29]:
salaries = np.genfromtxt('data/salary.csv',delimiter=',')

In [37]:
print(f"mean={np.mean(salaries)}\nmedian={np.median(salaries)}\nstandard_Deviation={np.std(salaries)}\nvariance={np.var(salaries)}")

mean=55894.53879686138
median=48000.0
standard_Deviation=55170.37550939316
variance=3043770333.8474483
