In [1]:
import numpy as np

In [2]:
a = np.arange(11)**2

In [5]:
for i in a:
    print(int(i**(1/2)))

0
1
2
3
4
5
6
7
8
9
10


In [6]:
students=np.array(
[
    ['Alice','Gaurav','Manoj','Sharma'],
    [65,88,78,98],
    [75,88,96,44]
]
)

In [7]:
students

array([['Alice', 'Gaurav', 'Manoj', 'Sharma'],
       ['65', '88', '78', '98'],
       ['75', '88', '96', '44']], dtype='<U6')

In [10]:
for i in students:
    print(f"i = {i}")

i = ['Alice' 'Gaurav' 'Manoj' 'Sharma']
i = ['65' '88' '78' '98']
i = ['75' '88' '96' '44']


In [12]:
#we can iterate over all the elemets in the array, #Row major flattening - elements in a row apear together
for i in students.flatten():
    print(i)

Alice
Gaurav
Manoj
Sharma
65
88
78
98
75
88
96
44


In [13]:
students.flatten(order='F') #column major flattening

array(['Alice', '65', '75', 'Gaurav', '88', '88', 'Manoj', '78', '96',
       'Sharma', '98', '44'], dtype='<U6')

In [17]:
a=np.arange(12).reshape(3,4)

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
for i in np.nditer(a):  #row major form by default
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [20]:
for i in np.nditer(a,order='F'):  #column major form by default
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [21]:
students_flat=students.flatten()

In [22]:
students_flat

array(['Alice', 'Gaurav', 'Manoj', 'Sharma', '65', '88', '78', '98', '75',
       '88', '96', '44'], dtype='<U6')

In [23]:
students_iter = np.nditer(students)

In [24]:
students_iter

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
for i in np.nditer(a,order='F',flags = ['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [33]:
for arr in np.nditer(a, op_flags = ['readwrite']):
    arr[...] = arr * arr #arr[...] ellipsis denotes the current element in the array, here we are doing element by element multiplication

In [34]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [50]:
n = np.arange(16).reshape(2, 2, 2, 2) #4d means two 3d arrays where one 3d array is two 2d arrays

In [51]:
n

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [41]:
n[0][1][0][0]

4

In [43]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [45]:
for i in n:
    i[...]=i*i

In [46]:
n

array([[[[  0,   1],
         [  4,   9]],

        [[ 16,  25],
         [ 36,  49]]],


       [[[ 64,  81],
         [100, 121]],

        [[144, 169],
         [196, 225]]]])

In [47]:
v = np.arange(6).reshape(2,3)

In [48]:
v

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
n

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [52]:
np.dot(n,v)

array([[[[  3,   4,   5],
         [  9,  14,  19]],

        [[ 15,  24,  33],
         [ 21,  34,  47]]],


       [[[ 27,  44,  61],
         [ 33,  54,  75]],

        [[ 39,  64,  89],
         [ 45,  74, 103]]]])

In [54]:
np.nditer

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])