In [2]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\gaurav sharma\anaconda3\lib\site-packages (1.18.4)


In [3]:
import numpy as np

In [5]:
array_one= np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [7]:
numbers=[4,5,6,7]
array_two=np.array(numbers)
array_two

array([4, 5, 6, 7])

In [13]:
array_of_zeros=np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
array_of_ones=np.ones((3,4),dtype=np.int16)
array_of_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [12]:
array_of_empty=np.empty((2,3))
array_of_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
array_eye= np.eye(3) #sqaure matrix of size 3*3 or 3*3 array
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
array_of_evens = np.arange(2,20,2) #just like a range fn
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
array_of_floats = np.arange(0,3,.3) #np.array(np.arange(0,9,.9),dtype=np.int16) #with floating step size
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [59]:
array_2d = np.array( [[2,4,6],[3,5,7]] ) #passing a list of lists
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [48]:
array_2d01=np.array((np.zeros((1,3)),np.ones((1,3))),dtype=np.int16)

In [49]:
array_2d01
array_2d01.shape

(2, 1, 3)

In [44]:
array_2d.shape

(2, 3)

In [52]:
array_nd=np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [56]:
array_ones=np.ones_like(array_nd) # this will create an array of 1s with the size reference to array_nd
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])