In [1]:
import numpy as np

In [2]:
a = np.array([10,10,10])  #if the arrays are of the same shape they can be added element wise
b = np.array([5,5,5])

In [3]:
a+b

array([15, 15, 15])

In [4]:
a-b

array([5, 5, 5])

In [5]:
a*b #element wise operations and size of the resultant array will be same as the original arrays

array([50, 50, 50])

In [9]:
division = np.array((a/b),dtype=np.int16)

In [11]:
print(division)

[2 2 2]


In [13]:
a%3

array([1, 1, 1], dtype=int32)

In [14]:
a < 35 #each element of the array will be compared to 35 one by one

array([ True,  True,  True])

In [36]:
A = np.array( [[1,1],[0,1]])
B = np.array( [[2,0],[3,4]])

In [37]:
A*B   #corresponding element multiplication #size has too be same

array([[2, 0],
       [0, 4]])

In [38]:
A.dot(B)  #matrix multiplication = sum(all elements in row * all elements in column)

array([[5, 4],
       [3, 4]])

In [19]:
np.dot(A,B) 

array([[5, 4],
       [3, 4]])

#we can only multipy an m(row) * n(column) matrix with an n(row) * k(column) matrix
#the size of the result of dot matrix  will be m(row in first matrix) * k(column in second matrix)

# for dot product the number of coulmns of first matrix must match the no. of rows of the second matrix 

#a m*3 matrix can dor product by 3*k matrix

#in dot product there is always multplication of row vector to column vector

In [20]:
a *= 3 #multiply all the elements of a with 3

In [21]:
b += a #b=b+a

In [22]:
ages= np.array([12,4,5,8,7,4,55])

In [32]:
ages.max(axis=0)

55

In [24]:
ages.min()

4

In [25]:
ages.sum()

95

In [26]:
numbers=np.arange(12).reshape(3,4)

In [27]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
numbers.sum(axis=0) #axis=0 for columns

array([12, 15, 18, 21])

In [29]:
numbers.sum(axis=1) #axis=1 for rows

array([ 6, 22, 38])

In [30]:
numbers.min(axis=1)

array([0, 4, 8])

In [67]:
a = np.arange(12).reshape(3,4)
b = np.arange(8).reshape(4,2)

# the dot product of these will have size 3 * 2

In [68]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [62]:
np.dot(a,b)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])