In [1]:
import numpy as np

In [4]:
a = np.arange(11)**2 #square the array

In [5]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [6]:
a[0]

0

In [9]:
l=[]
for i in a:
    l.append(i)

In [10]:
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [12]:
np.sin(np.radians(l))

array([0.        , 0.01745241, 0.06975647, 0.15643447, 0.27563736,
       0.42261826, 0.58778525, 0.75470958, 0.89879405, 0.98768834,
       0.98480775])

In [13]:
a[-2] #second last elements

81

In [14]:
a[2:7]  #end range index will be excluded

array([ 4,  9, 16, 25, 36], dtype=int32)

In [15]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [16]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [17]:
a[3:]

array([  9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [19]:
a[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [20]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [22]:
students[0:2,2:4]

NameError: name 'students' is not defined

In [ ]:
student[:,1:2] #all the rows and column 1

In [ ]:
student[1:3,:] #all the columns and rows 1 and 2

In [ ]:
student[-1:] #all columns and last row as row index is -1

In [ ]:
student[-3:-1,-2:] #rows last 3rd and last 2nd row as -1 in not included plus columns starting -2 to end

In [ ]:
student[0,...] #first row (index is 0) and all columns

In [ ]:
students[...,1] #all rows with column at index 1